version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongodb


  fastapi:
    build: ./app
    container_name: fastapi
    ports:
      - 4850:4850
    depends_on:
      - db

  seeder:
    build: ./app/seeder
    container_name: seeder
    depends_on:
      - db


